# cpanm --installdeps --notest --skip-satisfied .
requires perl => 5.036;
requires 'Cpanel::JSON::XS';
requires 'IPC::Run';
requires 'Moo';
requires 'MooX::Options';
requires 'Term::ProgressBar';
requires 'Types::Standard';
